name: Docker Image CI

on:
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
    - main
  schedule:
  - cron: "0 2 * * 1-5"
  
jobs:

  build:

     name: Setup php
     uses: MilesChou/php-tools-action@v1.0.0

  
